#application: tutorial-trial
#version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/push-handlers/.*
  script: main.app
  login: admin

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: /stylesheets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
